-- 자유게시판 게시글 저장 테이블입니다.
-- Supabase SQL Editor에서는 반드시 일반 Run으로 실행하세요.

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 80),
  content text not null check (char_length(btrim(content)) between 1 and 10000),
  author_username text not null default '회원',
  author_role text not null default 'member' check (author_role in ('member', 'sub_admin', 'admin')),
  views integer not null default 0 check (views >= 0),
  created_at timestamptz not null default now()
);

alter table public.community_posts add column if not exists author_id uuid references auth.users(id) on delete cascade;
alter table public.community_posts add column if not exists title text;
alter table public.community_posts add column if not exists content text;
alter table public.community_posts add column if not exists author_username text default '회원';
alter table public.community_posts add column if not exists author_role text default 'member';
alter table public.community_posts add column if not exists views integer default 0;
alter table public.community_posts add column if not exists created_at timestamptz default now();

update public.community_posts
set
  author_username = coalesce(nullif(author_username, ''), '회원'),
  author_role = case
    when author_role in ('member', 'sub_admin', 'admin') then author_role
    else 'member'
  end,
  views = coalesce(views, 0),
  created_at = coalesce(created_at, now());

alter table public.community_posts alter column author_username set default '회원';
alter table public.community_posts alter column author_username set not null;
alter table public.community_posts alter column author_role set default 'member';
alter table public.community_posts alter column author_role set not null;
alter table public.community_posts alter column views set default 0;
alter table public.community_posts alter column views set not null;
alter table public.community_posts alter column created_at set default now();
alter table public.community_posts alter column created_at set not null;

alter table public.community_posts enable row level security;

grant select, insert on public.community_posts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "community_posts_select_approved_members" on public.community_posts;
create policy "community_posts_select_approved_members"
on public.community_posts
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_posts_insert_own_approved_members" on public.community_posts;
create policy "community_posts_insert_own_approved_members"
on public.community_posts
for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);
