-- 자유게시판 댓글과 좋아요/싫어요 저장 테이블입니다.
-- Supabase SQL Editor에서는 반드시 일반 Run으로 실행하세요.
-- Run and enable RLS는 사용하지 마세요. 이 파일 안에서 RLS를 직접 켭니다.

create table if not exists public.community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.community_posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_username text not null default '회원',
  author_role text not null default 'member' check (author_role in ('member', 'sub_admin', 'admin')),
  content text not null check (char_length(btrim(content)) between 1 and 3000),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.community_post_reactions (
  post_id bigint not null references public.community_posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

alter table public.community_comments enable row level security;
alter table public.community_post_reactions enable row level security;

grant select, insert, update, delete on public.community_comments to authenticated;
grant select, insert, update, delete on public.community_post_reactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "community_comments_select_approved_members" on public.community_comments;
create policy "community_comments_select_approved_members"
on public.community_comments
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_comments_insert_own_approved_members" on public.community_comments;
create policy "community_comments_insert_own_approved_members"
on public.community_comments
for insert
to authenticated
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_comments_update_own_approved_members" on public.community_comments;
create policy "community_comments_update_own_approved_members"
on public.community_comments
for update
to authenticated
using (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
)
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_comments_delete_own_approved_members" on public.community_comments;
create policy "community_comments_delete_own_approved_members"
on public.community_comments
for delete
to authenticated
using (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reactions_select_approved_members" on public.community_post_reactions;
create policy "community_reactions_select_approved_members"
on public.community_post_reactions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reactions_insert_own_approved_members" on public.community_post_reactions;
create policy "community_reactions_insert_own_approved_members"
on public.community_post_reactions
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reactions_update_own_approved_members" on public.community_post_reactions;
create policy "community_reactions_update_own_approved_members"
on public.community_post_reactions
for update
to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
)
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reactions_delete_own_approved_members" on public.community_post_reactions;
create policy "community_reactions_delete_own_approved_members"
on public.community_post_reactions
for delete
to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);
