-- 자유게시판 신고, 게시글 수정/삭제, 운영자 삭제 권한 설정입니다.
-- Supabase SQL Editor에서는 반드시 일반 Run으로 실행하세요.
-- Run and enable RLS는 사용하지 마세요. 이 파일 안에서 필요한 정책을 직접 설정합니다.

alter table public.community_posts add column if not exists updated_at timestamptz;

create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reporter_username text not null default '회원',
  reporter_role text not null default 'member' check (reporter_role in ('member', 'sub_admin', 'admin')),
  target_type text not null check (target_type in ('post', 'comment')),
  post_id bigint not null references public.community_posts(id) on delete cascade,
  comment_id bigint references public.community_comments(id) on delete cascade,
  target_title text not null default '제목 없음',
  target_content text not null default '',
  target_author_username text not null default '회원',
  created_at timestamptz not null default now(),
  constraint community_reports_target_check check (
    (target_type = 'post' and comment_id is null)
    or (target_type = 'comment' and comment_id is not null)
  )
);

create unique index if not exists community_reports_one_post_report_per_user
on public.community_reports (reporter_id, post_id)
where target_type = 'post' and comment_id is null;

create unique index if not exists community_reports_one_comment_report_per_user
on public.community_reports (reporter_id, comment_id)
where target_type = 'comment' and comment_id is not null;

alter table public.community_reports enable row level security;

grant select, insert, update, delete on public.community_posts to authenticated;
grant select, insert, update, delete on public.community_comments to authenticated;
grant select, insert, delete on public.community_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "community_posts_update_own_approved_members" on public.community_posts;
create policy "community_posts_update_own_approved_members"
on public.community_posts
for update
to authenticated
using (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
)
with check (
  author_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_posts_delete_own_or_staff" on public.community_posts;
create policy "community_posts_delete_own_or_staff"
on public.community_posts
for delete
to authenticated
using (
  (
    author_id = auth.uid()
    and exists (
      select 1
      from public.profiles as profiles
      where profiles.id = auth.uid()
        and (
          coalesce(profiles.is_approved, false) = true
          or coalesce(profiles.is_admin, false) = true
          or profiles.role in ('admin', 'sub_admin')
        )
        and coalesce(profiles.is_rejected, false) = false
        and coalesce(profiles.is_suspended_permanently, false) = false
        and not (
          profiles.suspension_starts_at is not null
          and profiles.suspension_ends_at is not null
          and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
        )
    )
  )
  or exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_comments_delete_staff" on public.community_comments;
create policy "community_comments_delete_staff"
on public.community_comments
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reports_insert_own_approved_members" on public.community_reports;
create policy "community_reports_insert_own_approved_members"
on public.community_reports
for insert
to authenticated
with check (
  reporter_id = auth.uid()
  and exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_approved, false) = true
        or coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reports_select_staff" on public.community_reports;
create policy "community_reports_select_staff"
on public.community_reports
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);

drop policy if exists "community_reports_delete_staff" on public.community_reports;
create policy "community_reports_delete_staff"
on public.community_reports
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles as profiles
    where profiles.id = auth.uid()
      and (
        coalesce(profiles.is_admin, false) = true
        or profiles.role in ('admin', 'sub_admin')
      )
      and coalesce(profiles.is_rejected, false) = false
      and coalesce(profiles.is_suspended_permanently, false) = false
      and not (
        profiles.suspension_starts_at is not null
        and profiles.suspension_ends_at is not null
        and now() between profiles.suspension_starts_at and profiles.suspension_ends_at
      )
  )
);
